### ISSUE TITLE
No icons in demo on chrome/windows 7

### ISSUE THREAD

**Issue by jcubic** [jonathantneal/media-player#1]
In chrome/windows 7 the demo look different than the screenshot:

![image](https://user-images.githubusercontent.com/280241/29717351-1ededfe2-89af-11e7-8e10-b48bf61e899d.png)

**Comment by jonathantneal** [comment]
Thanks so much for reporting this.  Generated SVGs can be fickle.  Let me look into this and get back to you.

**Comment by jhpratt** [comment]
~Confirming this on Chrome in Linux.~

I misread the original issue. See comments below.

**Comment by jonathantneal** [comment]
@jhpratt, @jcubic, are the icons working @ https://jonathantneal.github.io/media-player/ ?

That site runs off the `gh-pages` branch, which I’ve switched over to use the upcoming v1 version. If that works for you, I will release v1 immediately.

**Comment by jhpratt** [comment]
It's the RTL layout that shows like that for me. The page you linked to looks as expected.

**Comment by jonathantneal** [comment]
@jhpratt, thanks for the fast response! To confirm, you are saying that the icons aren’t showing @ https://jonathantneal.github.io/media-player/rtl.html ?

**Comment by jhpratt** [comment]
@jonathantneal I'm seeing this. Not sure what's causing it.

![screenshot from 2017-08-29 11-35-29](https://user-images.githubusercontent.com/3161395/29829811-6221a918-8cae-11e7-8d64-e37b42da07da.png)

(sorry, misread the original issue, but it's still something)

**Comment by jonathantneal** [comment]
That looks right. That’s a right-to-left page translated into Hebrew to demonstrate how RTL is handled. Notice that the icons are also flipped.

The demo could be better, because I have the video player stacked atop the audio player, and that looks kind of weird. What issue are you having?

**Comment by jhpratt** [comment]
Ah, I assumed they were both for the video player. Do RTL languages use reversed icons? I didn't think so, but I also don't speak Arabic/Hebrew/etc.

I didn't test anything, just the visual :) Maybe it's not an issue at all!

**Comment by jonathantneal** [comment]
@jhpratt, to be honest, I really expected them to be, based on what I saw going on with text, and how the play button points in the direction of the flow, but now I see this:

> Just go for the normal left to right bar because its the norm on almost every player
—
 https://www.reddit.com/r/learn_arabic/comments/4rk2po/designing_arabic_language_video_player_need_help/

And this

> Do not mirror media playback or progress bars. The direction of these elements represents the direction of the tape, not the direction of time.
— https://material.io/guidelines/usability/bidirectionality.html#bidirectionality-localization

However, Material doesn’t show the play button, explicitly, so I’m not certain.

**Comment by jonathantneal** [comment]
I’m asking on Twitter about RTL play controls and sliders.

https://twitter.com/jon_neal/status/902559754974875648

**Comment by jhpratt** [comment]
@jonathantneal I looked at a couple Arabic sites for examples. Al Jazeera is of course based in the Middle East, while the others are not. However, none of them reverse the play symbol (or the volume, for that matter).

[Al Jazeera](http://www.aljazeera.net/portal)
[BBC](http://www.bbc.com/arabic)
[CNN](https://arabic.cnn.com/)

I think it's safe to say if native Arabic sites don't do it, that's not how it is. I've also sent a message out to a native Arabic speaker I know to see what they have to say.

**Comment by jonathantneal** [comment]
Well, that just makes the player a lot easier. I’d like to get additional verification before I simplify the app even further.

**Comment by jonathantneal** [comment]
This developer worked on Firefox OS:

> People everywhere including MENA region used the same controls in CD players etc.. therefore it should be the same
— https://twitter.com/AhmedNefzaoui/status/902663005992824832

And in an article he wrote for Mozilla:

> Please don’t RTL the media player buttons.
— https://hacks.mozilla.org/2015/09/building-rtl-aware-web-apps-and-websites-part-1/

So, the player is going to become even smaller. :) The language support still makes it international-safe, but it’s not as impressive to me. That’s okay. The goal is not to create clever software. It’s to create good software.
