### ISSUE TITLE
Repeat/loop example

### ISSUE THREAD

**Issue by zomars** [jonathantneal/media-player#10]
Thanks so much for making this player, I was wondering if this player has any loop/repeat capabilities, if so how could achieve this?

**Comment by jonathantneal** [comment]
Hi @zomars. Does the example @ https://jonathantneal.github.io/media-player/ work for you? In the looped video near the top of the page, it uses this markup:

```html
<video
  class="media-player"
  src="https://diveinto.org/media/uscenes_h-264_hd_test.mp4"
  poster="https://diveinto.org/media/uscenes_h-264_hd_test.jpg"
  controls
  loop
 ></video>
```

**Comment by zomars** [comment]
Yes, thank you! Only one detail, can the loop be toggle via UI?

**Comment by jonathantneal** [comment]
It cannot be toggled via UI unless you add the button. You can change the UI and hook into anything the media can do.
