### ISSUE TITLE
Add more features

### ISSUE THREAD

**Issue by elraghifary** [jonathantneal/media-player#5]
This is great player and lightweight!

Can you add more feature like forward 5 seconds and backward 5 seconds button or specific time?
And also playback rate to slow or faster music.

Thanks.

**Comment by cferdinandi** [comment]
"Thanks for the free thing, can you do more free work for me."

This isn't my repo, and I'm not trying to be mean, but I want you to know how comments like this often come across.

Those are interesting ideas. Maybe you could try to bolt them in an submit a PR?

**Comment by jonathantneal** [comment]
I think this is great idea, @elraghifary. Sorry I haven’t had time to respond to this repo.

@cferdinandi, @elraghifary. I didn’t mean to ignore this. It just hasn’t been in the scope of work I’m in, and I accidentally forgot about the ping when it first arrived. It happens, and I wish there were a way to reactivate these in my view.

My free time has been considerably drained. The other day Facebook’s Create React App integrated one of my projects, and so I’m in tizzy trying to keep up with that.

And then there’s cssdb and all the PostCSS plugins. And then there’s normalize.css. And I’m probably forgetting something else.

By the time my job is accounted for, and my kids are tucked in bed, and I’m not trying to spend some time with Christina — I do try to get these things, and I can tell you after 7 years that _most of the time_ I really do.

Sorry for the tangent. I don’t want anyone to feel discouraged.
