### ISSUE TITLE
Video/Audio Controls ignore data-options settings

### ISSUE THREAD

**Issue by amil-m** [jonathantneal/media-player#8]
The controls on the demo pages ignore the settings set in the data-options settings. Is there a way to fix this? The playlist demo for instance has download set to false, but it still shows in Safari, Firefox and Chrome.

**Comment by jonathantneal** [comment]
I’ll look into this.

**Comment by jonathantneal** [comment]
There isn‘t an option to read from a `data-options` attribute. You can implement it yourself, though, as I did in the demo:

```js
new MediaPlayer(YOUR_DOM_ELEMENT, JSON.parse(YOUR_DOM_ELEMENT.getAttribute('data-options')));
```

Also, in the playlist demo, I do not have the download set to not display. Those options are not really doing anything.
