### ISSUE TITLE
Where are the icons?

### ISSUE THREAD

**Issue by SilverWolf32** [jonathantneal/media-player#9]
I just added this to my Electron project through npm, and all the buttons are blank (and huge).

In the README, it says this:

> Media Player **and its icons** use the CC0 “No Rights Reserved” license.
<sub>_(emphasis added)_</sub>

Does this mean the in-player icons, or the logo?

If it's the player icons, are the ones in the demo included with the project or otherwise available somewhere? If so, where can I find them?

**Comment by jonathantneal** [comment]
I did a bad job getting those icons into the project. Yes, the ones from the demo are the icons I am referring to.
